'use client';
import { useEffect } from 'react';
import { Bell, Plus } from 'lucide-react';
import Link from 'next/link';
import { PageHeader, PageShell, RequestCard } from '@/components/community-member/ui';
import { useRequestStore } from '@/stores/request.store';

export default function CommunityMemberDashboard() {
  const { requests, requester, loadRequesterContext, loadMyRequests, isLoading, error } = useRequestStore();
  useEffect(() => { void loadRequesterContext(); void loadMyRequests(); }, [loadRequesterContext, loadMyRequests]);
  const canCreate = requester?.membershipStatus === 'Active' && (!requester.cooldownUntil || new Date(requester.cooldownUntil).getTime() <= Date.now());
  return <PageShell><PageHeader eyebrow="Community Member" title="Welcome back, Amaka" description="Track your blood requests and coordinate donor confirmations." action={<button aria-label="Notifications" className="flex size-11 items-center justify-center rounded-full border border-(--color-border-default) bg-white text-(--color-text-secondary)"><Bell className="size-5" /></button>} />
    {error ? <div className="mb-5 rounded-(--radius-lg) border border-(--color-danger-soft) bg-(--color-danger-soft) p-4 text-sm text-(--color-danger)">{error}</div> : null}
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-(--color-text-muted)">Membership</p><p className="mt-2 text-lg font-bold">{requester?.membershipStatus ?? 'Loading...'}</p></div><div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-(--color-text-muted)">My requests</p><p className="mt-2 text-lg font-bold">{requests.length}</p></div><div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-(--color-text-muted)">Open requests</p><p className="mt-2 text-lg font-bold">{requests.filter((r) => r.status === 'Open').length}</p></div></div>
    {canCreate ? <Link href="/community/requests/new" className="mb-6 flex items-center justify-between rounded-(--radius-xl) bg-(--color-brand-primary) p-5 text-white shadow-(--shadow-md) hover:bg-(--color-brand-primary-hover)"><div><p className="text-sm font-bold">Create Blood Request</p><p className="mt-1 text-xs text-white/75">Find matched donors through LIFESOURCE.</p></div><span className="flex size-10 items-center justify-center rounded-full bg-white/15"><Plus className="size-5" /></span></Link> : <div className="mb-6 rounded-(--radius-xl) border border-(--color-border-default) bg-(--color-surface-subtle) p-5"><p className="text-sm font-bold text-(--color-text-muted)">Create Blood Request</p><p className="mt-1 text-xs text-(--color-text-muted)">You must have active membership and no requester cooldown.</p></div>}
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-wide text-(--color-text-secondary)">My Blood Requests</h2><Link href="/community/requests/new" className="text-sm font-semibold text-(--color-brand-primary)">New request</Link></div>{isLoading && requests.length === 0 ? <div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-10 text-center text-sm text-(--color-text-muted)">Loading requests...</div> : requests.length === 0 ? <div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-10 text-center text-sm text-(--color-text-muted)">No requests yet.</div> : <div className="grid gap-3 md:grid-cols-2">{requests.map((request) => <RequestCard key={request.id} request={request} href={`/community/requests/${request.id}`} />)}</div>}</section>
  </PageShell>;
}
