'use client';
import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { BackLink, Button, PageHeader, PageShell } from '@/components/community-member/ui';
import { requestService } from '@/services/request.service';
import { useRequestStore } from '@/stores/request.store';
import type { BloodRequest } from '@/features/request/types';

export default function AcceptRequestPage() { const { requestId } = useParams<{ requestId: string }>(); const router = useRouter(); const [request, setRequest] = useState<BloodRequest | null>(null); const { acceptRequest, donor, error, clearError } = useRequestStore(); const [loading, setLoading] = useState(false); useEffect(() => { void requestService.getRequest(requestId).then(setRequest); }, [requestId]); const accept = async () => { clearError(); setLoading(true); try { const acceptance = await acceptRequest(requestId); router.push(`/donor/requests/${requestId}/accepted?code=${encodeURIComponent(acceptance.verificationCode)}`); } catch { } finally { setLoading(false); } }; if (!request) return <PageShell><BackLink href={`/donor/requests/${requestId}`} /><div className="rounded-(--radius-xl) border border-(--color-border-default) bg-white p-8 text-center text-sm text-(--color-text-muted)">Loading...</div></PageShell>; const inCooldown = !!donor?.cooldownUntil && new Date(donor.cooldownUntil).getTime() > Date.now(); return <PageShell><BackLink href={`/donor/requests/${requestId}`} /><PageHeader title="Confirm acceptance" description="Review the request before committing to donate." /><div className="mx-auto max-w-xl space-y-5 rounded-(--radius-xl) border border-(--color-border-default) bg-white p-5 md:p-6"><div className="rounded-(--radius-xl) bg-(--color-surface-subtle) p-4"><p className="text-lg font-extrabold">{request.bloodType} blood</p><p className="mt-1 text-sm font-semibold">{request.hospital.name}</p><p className="mt-1 text-xs text-(--color-text-muted)">{request.id} · {request.confirmedDonors}/{request.donorsNeeded} confirmed</p></div><div className="rounded-(--radius-lg) bg-(--color-info-soft) p-4 text-sm leading-relaxed text-(--color-info)">By accepting, you commit to donating at the listed hospital. LIFESOURCE will generate a private verification code for this donor/request pair.</div>{error ? <div className="rounded-(--radius-lg) bg-(--color-danger-soft) p-4 text-sm text-(--color-danger)">{error}</div> : null}<Button onClick={accept} disabled={loading || inCooldown}>{inCooldown ? 'Unavailable during cooldown' : loading ? 'Accepting...' : 'Confirm acceptance'}</Button></div></PageShell>; }
