import { CARequests } from "./requests-types";
export const MOCK_REQUESTS: CARequests[] = [
  {
    id: "REQ-0041",
    requester: "Amaka Okafor",
    blood: "O+",
    needed: 4,
    conf: 3,
    hospital: "Lagos Island Gen.",
    urgency: "High",
    status: "Open",
    date: "Dec 12",
  },
  {
    id: "REQ-0039",
    requester: "Bode Lawal",
    blood: "A+",
    needed: 2,
    conf: 1,
    hospital: "LUTH",
    urgency: "—",
    status: "Open",
    date: "Dec 10",
  },
  {
    id: "REQ-0038",
    requester: "Chioma Eze",
    blood: "AB+",
    needed: 12,
    conf: 12,
    hospital: "AKTH",
    urgency: "High",
    status: "Fulfilled",
    date: "Dec 5",
  },
  {
    id: "REQ-0025",
    requester: "Danladi Usman",
    blood: "O-",
    needed: 1,
    conf: 1,
    hospital: "Garki Hospital",
    urgency: "—",
    status: "Fulfilled",
    date: "Nov 20",
  },
];
