export const STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT — Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const LGAS: Record<string, string[]> = {
  Lagos: [
    "Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Epe",
    "Eti-Osa",
    "Ibeju-Lekki",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Kosofe",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi-Isolo",
    "Shomolu",
    "Surulere",
  ],

  "FCT — Abuja": [
    "Abaji",
    "Bwari",
    "Gwagwalada",
    "Kuje",
    "Kwali",
    "Municipal Area Council",
  ],

  Kano: [
    "Dala",
    "Fagge",
    "Gwale",
    "Kano Municipal",
    "Kumbotso",
    "Nassarawa",
    "Tarauni",
    "Ungogo",
  ],

  Rivers: [
    "Bonny",
    "Degema",
    "Eleme",
    "Emohua",
    "Etche",
    "Ikwerre",
    "Obio-Akpor",
    "Okrika",
    "Port Harcourt",
  ],

  Oyo: [
    "Afijio",
    "Akinyele",
    "Atiba",
    "Egbeda",
    "Ibadan North",
    "Ibadan North-East",
    "Ibadan North-West",
    "Ibadan South-East",
    "Ibadan South-West",
    "Ibarapa Central",
    "Ido",
    "Lagelu",
    "Ogbomosho North",
    "Oyo East",
    "Oyo West",
    "Saki East",
    "Saki West",
    "Surulere",
    "Oluyole",
  ],

  Anambra: [
    "Aguata",
    "Anambra East",
    "Awka North",
    "Awka South",
    "Idemili North",
    "Idemili South",
    "Nnewi North",
    "Nnewi South",
    "Onitsha North",
    "Onitsha South",
  ],
};

export const DEFAULT_LGAS = [
  "Central LGA",
  "East LGA",
  "West LGA",
  "North LGA",
  "South LGA",
];